
import localFont from "next/font/local";
import "./globals.css";
import SplashScreenManager from "../components/SplashScreenManager";
import Navbar from "@/components/Navbar";
import hara from "next/font/local"


// const hara = localFont({
//   src:"fonts/Hara.ttf",
//   variable:"--font-haras"
// });

const font = hara({ src: "../public/fonts/Hara.ttf" })

export const metadata = {
  title: "Iskon Hazaribagh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

 

  return (
    <html lang="en">
      <body
        className={` ${font.className} antialiased`}
      >
      <SplashScreenManager>
      <Navbar/>
      {children}
      </SplashScreenManager>
      
      
      </body>
    </html>
  );
}
