
import localFont from "next/font/local";
import "./globals.css";
import SplashScreenManager from "../components/SplashScreenManager";
import Navbar from "@/components/Navbar";
import hara from "next/font/local"
import tnr from "next/font/local"
import Footer from "@/components/Footer";
// const geistSans = localFont({
//   src: "../public/fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

export const tinr=tnr({ src: "../public/fonts/Timesnewroman.ttf" })
export const haRa = hara({ src: "../public/fonts/Hara.ttf" })


 const metadata = {
  title: "Iskon Hazaribagh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

 

  return (
    <html lang="en">
      <body
        className={`  antialiased`}
      >
      <SplashScreenManager>
      <Navbar/>
      {children}
     
      </SplashScreenManager>
      
      
      </body>
    </html>
  );
}
